select distinct b.clientname,b.Category,b.HomePageLink,a.MerchandiseCategory,a.MerchandiseSubCat,a.Category,a.RealCategory
from vw_MerchandiseCategory a
join vw_catinfo b
on a.CategoryCodeId=b.CategoryCodeId
join mt2sql17.sql17.dbo.acfvdisquerypage c
on c.category=a.RealCategory
where FVCCType in (4,6)
and (c.category!=a.Category or c.MerchandiseCategory!=a.MerchandiseCategory or c.MerchandiseSubCat!=a.MerchandiseSubCat)
and a.RealCategory in ('Beverage Makers',
'Bread Makers',
'Cappuccino/Espresso Makers',
'Citrus Juicers',
'Coffee Grinders/Mills',
'Coffee Makers',
'Coffee Makers Single Cup',
'Convection Ovens',
'Countertop Blenders',
'Deep Fryers',
'Dishwashers',
'Electric Burners',
'Electric Griddles',
'Electric Kettles',
'Electric Knives',
'Electric Skillets',
'Electric/Indoor Grills',
'Fondue',
'Food Choppers',
'Food Processors',
'Food Savers/Sealers',
'Hand Mixers',
'Hand/Immersion Blenders',
'Ice Cream Makers',
'Ice Makers',
'Juice Extractors',
'Kitchen Scales',
'Meat Grinders/Slicers',
'Microwaves',
'Milkshake Makers',
'Pizza Makers',
'Popcorn Makers',
'Pressure Cookers',
'Refrigerators/Freezers',
'Rice Cookers',
'Roaster Ovens',
'Sandwich Makers',
'Slow Cookers',
'Snack/Entree Makers',
'Stand Mixers',
'Steamers',
'Stoves',
'Toaster Ovens',
'Toasters',
'Treat Makers',
'Waffle/Pancake Makers',
'Warmers/Hot Plates',
'Washers/Dryers')
and b.Category in ('mmmac',
'acoPep',
'ahlPeP',
'ave',
'bfsPeP',
'buac',
'bozPep',
'BHPAC',
'cwgPeP',
'CVSPeP',
'dfusPeP',
'ddh',
'dolgPep',
'fmdPeP',
'fmdPP',
'firsPEP',
'fredPEP',
'HALPEP',
'HPHPEP',
'impPEP',
'gmcPeP',
'kyfPeP',
'kkmAC',
'lid',
'fpuscPEP',
'acfvm',
'acfvr',
'acfvmtr',
'mglPEP',
'nwPep',
'nwrPeP',
'NAPEP',
'offPeP',
'osac',
'pclPep',
'pca',
'PRGPeP',
'pchPep',
'raPep',
'rouPep',
'slotPEP',
'sePEP',
'sfmPeP',
'staPEP',
'stbPep',
'tarPep',
'tarPP',
'tfmPeP',
'TmgPEP',
'tsmPeP',
'uniPep',
'vciPeP',
'walPeP',
'FSIWLMPEP',
'wlmPeP',
'wlmPP',
'wbcpac',
'wilPeP')
order by 1,6,7,4,5