
select distinct clientname,b.Category,HomePageLink,a.realCategory,ClientServer,MCTemplateID,b.categorycodeid
from vw_MerchandiseCategory a
 join vw_catinfo b 
 on a.CategoryCodeId=b.CategoryCodeId
where a.realCategory in ('Action Figures'
,'Active Games'
,'Air Conditioners'
,'Artificial Trees/Flowers'
,'As Seen On TV'
,'Asphalt Patch/Sealer'
,'Auto Service'
,'Bakeware'
,'Bath Rugs/Tub Mats/Sets'
,'Bathroom Acc/Scales'
,'Beach Towels'
,'Beach/Sand Box Toys'
,'Bed Spreads/Shams'
,'Bicycles/Accessories'
,'Blankets/Comforters'
,'Blenders'
,'Board Games'
,'Bread Makers'
,'Cabinetry'
,'Camping'
,'Canister Sets'
,'Card Games'
,'Carpet Shampooers/Steamers'
,'Childrens Bedding'
,'Childrens Clothing'
,'Closet/Storage'
,'Computer Accessories'
,'Computer Hardware'
,'Computer Software'
,'Computers'
,'Concrete/Grout/Mortar'
,'Construction Materials - Other'
,'Consumer Elec - Other'
,'Convection Ovens'
,'Cookware'
,'Coolers'
,'Crockpot/Slow Cooker'
,'Curling Irons/Brushes'
,'Cutlery'
,'Dehumidifiers'
,'Dehydrators'
,'Dental Appliances'
,'Dishes'
,'Dolls'
,'Door Bells/Chimes'
,'Door Hardware'
,'Drinking Glasses'
,'Drinks Btls/Insulated Cntnrs'
,'Electric Blankets'
,'Electric Kettles'
,'Electric Knives'
,'Electric Skillets'
,'Electrical Supplies'
,'Electronic Games'
,'Electronics - Other'
,'Elevation Products'
,'Eurosealers'
,'Fans'
,'Fire Logs'
,'Fire Starters'
,'Fireplace Accessories'
,'Flatware'
,'Folding Camp/Beach Chairs'
,'Food Choppers'
,'Food Processors'
,'Food Steamers'
,'Foot Baths'
,'Fryers'
,'Furniture'
,'Garage Door Openers'
,'Garbage Cans'
,'Garden Hoses/Sprinklers'
,'Garden Tools - Power'
,'Garden/Walkway Lighting'
,'Gas Grills'
,'Gloves - Protective'
,'Hand Tools'
,'Hardware - Other'
,'Hardware - Storage'
,'Hardware Shelving'
,'Heaters'
,'Heating Pads'
,'Home - Other'
,'Home Security Systems'
,'Hosiery'
,'Hunting/Fishing'
,'Indoor Grills'
,'Infant/Toddler Clothing'
,'Installed Timers'
,'Irons'
,'Juicers/Juice Extractors'
,'Kettles'
,'Kitchen - Other'
,'Kitchen Gadgets'
,'Kitchen Rugs/Doormats'
,'Kitchen Towels/Pot Holders'
,'Lamps'
,'Laundry Basket/Hamper'
,'Lawn Furniture & Accessories'
,'Light Bulbs'
,'Luggage'
,'Lumber'
,'Massagers'
,'Mattresses'
,'Microwaves'
,'Mixers'
,'Molding/Doweling'
,'Motor Vehicle Care/Acc'
,'Nails/Screws/Other'
,'Office Accessories'
,'Office Machines - Other'
,'Outdoor Plants/Shrubs/Trees'
,'Outdoor Wall/Pole Lighting'
,'Paint Brushes/Rollers'
,'Paint/Stains/Sealers'
,'Paint-Spray Paint'
,'Park Benches'
,'Patio & Beach Umbrellas'
,'Patio Heaters/Portable Hearths'
,'PDAs'
,'Phone Accessories'
,'Place Mats'
,'Planters'
,'Plasticware'
,'Plumbing Supplies'
,'Plush Figures'
,'Pool Supplies'
,'Pool/Spa Accessories'
,'Pools/Wading Pools'
,'Popcorn Maker'
,'Portable A/V Accessories'
,'Portable Gazebos/Tenting'
,'Power Tools'
,'Projectors'
,'Propane Tanks'
,'Puzzles'
,'Radios'
,'Recreational Floatation'
,'Rice Cookers'
,'Ride Ons'
,'Roaster'
,'Rope/Clothesline'
,'Rotisseries'
,'Rugs'
,'Safety Gear'
,'Sandwich Makers'
,'Sewing Machines'
,'Sheets/Pillowcases'
,'Signs'
,'Sm Appl - Other'
,'Smoke/CO Detectors'
,'Spark Plugs'
,'Speakers'
,'Sports Accessories'
,'Sports Bags'
,'Sports Equipment'
,'Sprinkler Systems'
,'Sunglasses'
,'Tablecloths/Napkins'
,'Tea Makers'
,'Thermoses'
,'Throw Pillows'
,'Tires'
,'Toaster Ovens'
,'Toasters'
,'Tools - Other'
,'Toys - Other'
,'Trading Cards'
,'TVs'
,'Vacuum Accessories'
,'Vacuum Cleaners'
,'Vaporizers/Humidifiers'
,'Vehicles'
,'Video Game Software'
,'Waffle Makers'
,'Waste baskets'
,'Water Filtration'
,'Water Filtration - Installed'
,'Womens Accessories'
,'Work Lights'
,'Work Tables/Benches'
,'Automotive - Other'
,'Canning'
,'Cellular Phones/Service'
,'Childrens Safety'
,'Childrens Transport'
,'Electric Hair Removal'
,'Food Storage'
,'Gardening Accessories'
,'Hair Dryers'
,'Hairsetters'
,'Internet Services'
,'Landscape'
,'Mens Accessories'
,'Motor Oil'
,'Pre-Rec Movie Sales'
,'Pre-Rec Music'
,'Seasonal Décor'
,'Storage Containers'
)
and clientname like '%numer%'
--and clientname in ('Numerator - Production (Consumables)','Numerator - AC Integrated Data Test','Numerator - Digital Data')
--and (b.Category Like '%CA'Or b.Category Like '%CA50'Or b.Category Like '%CAN'Or b.HomePageLink Like '%CAN%' and b.clientname not like '%numera%' or FVCCType=3)
and clientpdt=1 and ClientServer in ('mt2sql04','mt2sql07','mt2sql08','mt2sql11')
order by 3